"""empty message

Revision ID: 153c5ab6cb6e
Revises: 67a861069db2
Create Date: 2020-10-05 17:39:03.019701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153c5ab6cb6e'
down_revision = '67a861069db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genre3', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genre3')
    # ### end Alembic commands ###
