"""empty message

Revision ID: 33dd3bea6347
Revises: 9900ad87b659
Create Date: 2020-10-05 12:14:19.211092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33dd3bea6347'
down_revision = '9900ad87b659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewReleases', sa.Column('artists_id', sa.String(length=60), nullable=True))
    op.drop_column('NewReleases', 'artists_lookup_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewReleases', sa.Column('artists_lookup_url', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('NewReleases', 'artists_id')
    # ### end Alembic commands ###
