"""empty message

Revision ID: af14a3a4ef92
Revises: e769f06c2be7
Create Date: 2020-10-06 15:26:01.376978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af14a3a4ef92'
down_revision = 'e769f06c2be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=200), nullable=True),
    sa.Column('refresh_token', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NewReleases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('album_type', sa.String(length=10), nullable=True),
    sa.Column('artists', sa.String(length=200), nullable=True),
    sa.Column('artists_identifier', sa.String(length=60), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('genre1', sa.String(length=100), nullable=True),
    sa.Column('genre2', sa.String(length=100), nullable=True),
    sa.Column('genre3', sa.String(length=100), nullable=True),
    sa.Column('href', sa.String(length=100), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('artists_identifier', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    op.drop_table('NewReleases')
    op.drop_table('Credentials')
    # ### end Alembic commands ###
