"""empty message

Revision ID: b05b116b887a
Revises: 33dd3bea6347
Create Date: 2020-10-05 12:30:41.875675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05b116b887a'
down_revision = '33dd3bea6347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewReleases', sa.Column('artists_ids', sa.String(length=60), nullable=True))
    op.drop_column('NewReleases', 'artists_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewReleases', sa.Column('artists_id', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('NewReleases', 'artists_ids')
    # ### end Alembic commands ###
