"""empty message

Revision ID: e769f06c2be7
Revises: 153c5ab6cb6e
Create Date: 2020-10-05 18:11:16.813594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e769f06c2be7'
down_revision = '153c5ab6cb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('artists_identifier', sa.String(length=60), nullable=True))
    op.add_column('artists', sa.Column('followers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'followers')
    op.drop_column('artists', 'artists_identifier')
    # ### end Alembic commands ###
